### ISSUE TITLE
Volunteer 'donate' on menu renders for a second before redirecting

### ISSUE THREAD

**Issue by Gabri3l** [teamhacksmiths/food-drivr-frontend#15]
I noticed, that when a volunteer clicks on the user menu and then 'donate', the donation page renders for a second and then fades back to the home page. If the user is not allowed to donate we should consider not having 'donate' on the user menu.

**Comment by frankrobert** [comment]
I noticed this as well. Removing the button from the menu won't remove the option from a Driver user from typing '/donation' to attempt to access that page.

At the moment the redirect check is done in the Donations page at the ComponentDidMount lifecycle of the component. I initially did the check in the constructor, during the ComponentWillMount stage, and although that works, the console logs a lifecycle stage and recommends against doing that.

Will need to read up further and find an alternative solution. May need to be Router-level authing and rerouting for usertypes, rather then component-level.

**Comment by Gabri3l** [comment]
The issue is still present. I currently get this error:

`setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the DonationPage component`

I will investigate further to make sure it's fixed.

**Comment by Gabri3l** [comment]
I simply don't show the 'Donate' button for a driver based on the role of the user.
