### ISSUE TITLE
Signin autofill style is a pain to the eye

### ISSUE THREAD

**Issue by Gabri3l** [teamhacksmiths/food-drivr-frontend#24]
When autofilling the fields at signin, a yellow background appears with a pretty big impact on the visual effect.

**Comment by frankrobert** [comment]
This is actually a chrome specific issue. I had noticed this as well. Would take some fairly in depth css styling to correct this and we'd need to make sure that it's browser compliant if we're going to implement.

**Comment by RyanCCollins** [comment]
I totally agree!!! 👀 .  I found a solution and have done this.

**Comment by RyanCCollins** [comment]
Frank, this can be fixed in one line of css

```

down vote
accepted
I know it's stupid, but I think it works!

/* Change the white to any color ;) */
input:-webkit-autofill {
    -webkit-box-shadow: 0 0 0px 1000px white inset;
}
```

**Comment by Gabri3l** [comment]
Finally fixed! I add a specific autofill color depending on the form, I wish I could just set a transparent one but it's not possible =(
