### ISSUE TITLE
It is possible to signin with another user once logged in

### ISSUE THREAD

**Issue by Gabri3l** [teamhacksmiths/food-drivr-frontend#25]
After a use has already signed in, he/she can go back to the signin page and signin again with a different user. This is just a reminder as as topic of discussion, I don't know how this behavior is handled from the backend and if it can cause any issue.

**Comment by frankrobert** [comment]
We could lock out the user from the SignInPage component (similar to the dashboard / userprofile) when logged in. This could be a very simple solution to the problem.

**Comment by frankrobert** [comment]
Added an auth check to the routes. Tested and solves the issue.
