### ISSUE TITLE
User Dashboard does not render

### ISSUE THREAD

**Issue by frankrobert** [teamhacksmiths/food-drivr-frontend#29]
Come back to this and get the page to render.

**Comment by OfficialPhrank** [comment]
https://github.com/teamhacksmiths/food-drivr-frontend/tree/userprofile_dashboard_auth

This branch is correcting this issue.

**Comment by frankrobert** [comment]
This page does not exist.

**Comment by frankrobert** [comment]
Renamed Dashboard usermenu link to Home. Temporary resolution to this issue.
