### ISSUE TITLE
If a token is present in localStorage login does not return a Promise

### ISSUE THREAD

**Issue by Gabri3l** [teamhacksmiths/food-drivr-frontend#31]
In auth.js at line 8, there is an if statement that is broken.

If there is a token in the localStorage then it return "this.onChange(true)" while the calling function is expecting a promise, for this reason the app throws an error because it's waiting to execute .then or .catch on something that is NOT a Promise.

It's an easy fix but I'll leave you to make sure it follows your authentication logic, so it stays consistent with everything else.

**Comment by frankrobert** [comment]
https://github.com/teamhacksmiths/food-drivr-frontend/commit/1a9f1a5036adfdbbd5b77fff0df42d3586597698

This commit removed the issue. It ended up being a redundant piece of code. Thanks for finding it!
