### ISSUE TITLE
Donations from server not ordered by date

### ISSUE THREAD

**Issue by frankrobert** [teamhacksmiths/food-drivr-frontend#46]
Making a GET request to the API for all of the user's donations pulls all donations except does not sort them by date. See picture.

![ss 2016-06-07 at 08 01 32](https://cloud.githubusercontent.com/assets/4380529/15878720/4823b462-2ceb-11e6-8608-46d3e8d424e4.png)

**Comment by RyanCCollins** [comment]
`<Hacksmiths {...props} />`

**Comment by frankrobert** [comment]
@Gabri3l has this been sorted? Which commit?

**Comment by Gabri3l** [comment]
I will fix this this weekend! Stay tuned ahaha

**Comment by RyanCCollins** [comment]
Thanks @Gabri3l
