### ISSUE TITLE
"Save Profile"  behaving not as expected

### ISSUE THREAD

**Issue by Gabri3l** [teamhacksmiths/food-drivr-frontend#52]
I was playing around with the User Settings page and noticed this, when the user turns on the "Edit Mode" and changes the "Toggle Notification", the "Save Profile" button does not become active, so such change can not be saved if it's the only change applied. If another change is made, the "Save Profile" button becomes active and it's still active if the user goes back into "Edit Mode" (its state is reset only after refreshing the page). It seems like after the first edit "Save Profile" does not go back to a "Disabled" state.

Furthermore the "Toggle Notification" does not seem to be saved after hitting "Save Profile".

**Comment by frankrobert** [comment]
Fixed in latest commit. :)
