### ISSUE TITLE
Mobile Landing

### ISSUE THREAD

**Issue by RyanCCollins** [teamhacksmiths/food-drivr-frontend#58]
Hi guys.  Our beautiful design begins to show its weak spots on mobile.  We have an issue with overflow where a white area shows.  Also, I suggest on mobile, we make the .intro section a

```
min-height: calc(100vh - 6rem)
```

and that we get rid of some of the headers and P text.  Just the logo and the main header, plus button should be good.

I can do this if no one gets to it in the next couple days, but wanted to throw it out there.

Thanks!

**Comment by Gabri3l** [comment]
About the "white space" I will look into that but on my chrome dev tool in any mobile view that does not show, not even on my phone so it's kinda weird. I will work on fixing any bug here and there, if anyone notice new ones let me know and I will work on it!
