### ISSUE TITLE
Password Edit Text Field Hint Text not disappearing on input

### ISSUE THREAD

**Issue by frankrobert** [teamhacksmiths/food-drivr-frontend#68]
![screenshot_1](https://cloud.githubusercontent.com/assets/4380529/16536848/e4aeeda0-3fc5-11e6-8db1-6f3edab63350.png)

The tile is about as descriptive as I can get.

When you attempt to edit a user's password on the settings page, the dialog opens with 3 text fields for the Current Password, New Password, and New Password Confirmation. On input of any of these 3 text fields, the hint text will stay and overlap with the user's input.

**Comment by Gabri3l** [comment]
Fixed id on a branch I am working on, simply there were both floatingLabelText and hintText with the same value, only difference is that adding hintText it will stay on the field instead of disappearing upon user typing.
