### ISSUE TITLE
Can add Address List item without typing

### ISSUE THREAD

**Issue by frankrobert** [teamhacksmiths/food-drivr-frontend#75]
![screenshot_2](https://cloud.githubusercontent.com/assets/4380529/16541253/f4c83af8-404b-11e6-90de-0328fd5cf745.png)

If you hit the + symbol without typing anything, it will add the TRUE value into the list. This will also trigger state to Save Profile changes and this can _not_ be repeated without a hard refresh.

**Comment by Gabri3l** [comment]
Solved in commit  https://github.com/teamhacksmiths/food-drivr-frontend/commit/7c3f480e6e3d6e2a8ee98a1e9cbed799ec9d5145
