### ISSUE TITLE
Sign in spinner loops with no end

### ISSUE THREAD

**Issue by RyanCCollins** [teamhacksmiths/food-drivr-frontend#83]
Please fix!! Add some error handling so that it doesn't leave the user waiting forever (on signin).

**Comment by frankrobert** [comment]
@RyanCCollins I'm extremely certain that this is a Safari and localStorage issue. If that's the case, there's very little we're going to be able to do to resolve this

**Comment by RyanCCollins** [comment]
🤷‍♂️
